using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp3
{
    public class FieldAutogeneratedForPropertiesAccessors
    {
        private string name; // <- not required to write accessor body
        private string oldName; // <- is required to write accessor body

        // The token field enables you to write a property accessor body
        // without declaring an explicit backing field. Thus 'private string name' property
        // is no need anymore
        public string Name
        {
            get => field; // 'field' points to the automatically created backing field
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                    field = "Unknown";  // <- default value
                else
                    field = value.Trim();
            }
        }

        // Previously, we had a private field for name
        // For ex. oldName
        public string OldName
        {
            get => this.oldName;
            set
            {
                if (string.IsNullOrEmpty(value))
                {
                    this.oldName = "Unknown"; // <- default value
                }
                else
                {
                    this.oldName = value.Trim();

                }
            }
        }
    }
}